/**
 * Generates the service worker after Astro has built.
 *
 * Astro fingerprints its asset filenames, so the precache list cannot be
 * written by hand. This walks dist/, collects everything worth holding offline,
 * and stamps a version derived from the content so a deploy invalidates the old
 * cache rather than serving a stale shell forever.
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const DIST = join(ROOT, 'dist');

const PRECACHE_EXTENSIONS = new Set(['.html', '.css', '.js', '.svg', '.png', '.webmanifest', '.woff2', '.csv', '.webm']);
const SKIP = new Set(['sw.js', 'og.png', 'sitemap-index.xml', 'sitemap-0.xml', 'robots.txt']);

function walk(directory) {
  const found = [];
  for (const entry of readdirSync(directory)) {
    const full = join(directory, entry);
    if (statSync(full).isDirectory()) found.push(...walk(full));
    else found.push(full);
  }
  return found;
}

const files = walk(DIST)
  .map((file) => `/${relative(DIST, file).split(sep).join('/')}`)
  .filter((url) => {
    // The DuckDB engine is thirty four megabytes. Precaching it would make
    // installing the app a huge download for everyone, including the people who
    // never open the SQL tool. It is fetched on demand instead.
    if (url.startsWith('/duckdb/')) return false;
    const name = url.split('/').pop() ?? '';
    if (SKIP.has(name)) return false;
    const dot = name.lastIndexOf('.');
    return dot !== -1 && PRECACHE_EXTENSIONS.has(name.slice(dot));
  })
  // index.html files are reachable by their directory URL, which is what the
  // navigation handler will look up.
  .map((url) => (url.endsWith('/index.html') ? url.slice(0, -'index.html'.length) : url))
  .sort();

const hash = createHash('sha256');
// The worker's own logic is part of what a client is running, so a change here
// has to invalidate the cache the same way a changed asset does.
hash.update(readFileSync(fileURLToPath(import.meta.url)));
for (const url of files) {
  const path = url.endsWith('/') ? join(DIST, url, 'index.html') : join(DIST, url);
  hash.update(url);
  hash.update(readFileSync(path));
}
const version = hash.digest('hex').slice(0, 12);

const worker = `/**
 * alexmerced.app service worker. Generated by scripts/build-sw.mjs, do not edit.
 *
 * The whole site is static and small, so the strategy is simple: precache every
 * core page and asset on install, then keep that release together until an
 * update is activated. Optional large engines and models load on demand.
 */
const VERSION = '${version}';
const CACHE = 'alexmerced-app-' + VERSION;
const PRECACHE = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // A release is usable offline only when every required asset arrived.
      // A failed install leaves the previous worker and its cache intact.
      try {
        await cache.addAll(PRECACHE.map((url) => new Request(url, { cache: 'reload' })));
      } catch (error) {
        await caches.delete(CACHE);
        throw error;
      }
      // Updates wait until the user chooses Reload (or all old tabs close).
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith('alexmerced-app-') && key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});

// Servers often send "Vary: Origin" on scripts. Module scripts are fetched in
// cors mode while cache.addAll stores them from a no-cors request, so a strict
// match misses them entirely and the page loads without its JavaScript.
const MATCH = { ignoreVary: true };

async function staleWhileRevalidate(request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(request, MATCH);

  if (cached && PRECACHE.includes(new URL(request.url).pathname)) return cached;
  const network = fetch(request)
    .then(async (response) => {
      if (response && response.status === 200 && response.type === 'basic') {
        await cache.put(request, response.clone());
      }
      return response;
    })
    .catch(() => null);

  return cached || (await network) || Response.error();
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) {
    // Cache only the pinned speech runtime requested by an explicit model load.
    if (url.origin === 'https://cdn.jsdelivr.net' && url.pathname.startsWith('/npm/@huggingface/transformers@3.0.2/')) {
      event.respondWith((async () => {
        const cache = await caches.open('workspace-speech');
        const cached = await cache.match(request);
        if (cached) return cached;
        const response = await fetch(request);
        if (response.ok) await cache.put(request, response.clone());
        return response;
      })());
    }
    return;
  }
  if (url.pathname.startsWith('/duckdb/')) {
    event.respondWith((async () => {
      const cache = await caches.open('workspace-engines');
      const cached = await cache.match(request, MATCH);
      if (cached) return cached;
      const response = await fetch(request);
      if (response.ok) await cache.put(request, response.clone());
      return response;
    })());
    return;
  }

  // Navigations: serve the cached page, and fall back to the home page so a
  // deep link still opens something useful when offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE);
        const cached =
          (await cache.match(url.pathname, MATCH)) || (await cache.match(url.pathname + '/', MATCH));
        // Keep HTML paired with this release's fingerprinted scripts.
        if (cached) return cached;
        try {
          return await fetch(request);
        } catch {
          return (await cache.match('/', MATCH)) || Response.error();
        }
      })(),
    );
    return;
  }

  event.respondWith(staleWhileRevalidate(request));
});
`;

writeFileSync(join(DIST, 'sw.js'), worker, 'utf-8');
console.log(`service worker: ${files.length} files precached, version ${version}`);
